id: PYSEC-0000-CVE-2024-45230
details: An issue was discovered in Django 5.1 before 5.1.1, 5.0 before 5.0.9, and
  4.2 before 4.2.16. The urlize() and urlizetrunc() template filters are subject to
  a potential denial-of-service attack via very large inputs with a specific sequence
  of characters.
affected:
- package:
    name: django
    ecosystem: PyPI
    purl: pkg:pypi/django
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: "5.1"
    - fixed: 5.1.1
    - introduced: "5.0"
    - fixed: 5.0.9
    - introduced: "4.2"
    - fixed: 4.2.16
references:
- type: WEB
  url: https://docs.djangoproject.com/en/dev/releases/security/
- type: WEB
  url: https://groups.google.com/forum/#%21forum/django-announce
- type: ARTICLE
  url: https://www.djangoproject.com/weblog/2024/sep/03/security-releases/
aliases:
- CVE-2024-45230
modified: "2024-10-08T16:15:00Z"
published: "2024-10-08T16:15:00Z"
