id: PYSEC-0000-CVE-2024-45230
details: An issue was discovered in Django 5.1 before 5.1.1, 5.0 before 5.0.9, and
  4.2 before 4.2.16. The urlize() and urlizetrunc() template filters are subject to
  a potential denial-of-service attack via very large inputs with a specific sequence
  of characters.
aliases:
- CVE-2024-45230
modified: '2024-10-08T19:19:01.400873Z'
published: '2024-10-08T16:15:00Z'
references:
- type: WEB
  url: https://docs.djangoproject.com/en/dev/releases/security/
- type: WEB
  url: https://groups.google.com/forum/#%21forum/django-announce
- type: ARTICLE
  url: https://www.djangoproject.com/weblog/2024/sep/03/security-releases/
affected:
- package:
    name: django
    ecosystem: PyPI
    purl: pkg:pypi/django
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: '5.1'
    - fixed: 5.1.1
    - introduced: '5.0'
    - fixed: 5.0.9
    - introduced: '4.2'
    - fixed: 4.2.16
  versions:
  - '4.2'
  - 4.2.1
  - 4.2.10
  - 4.2.11
  - 4.2.12
  - 4.2.13
  - 4.2.14
  - 4.2.15
  - 4.2.2
  - 4.2.3
  - 4.2.4
  - 4.2.5
  - 4.2.6
  - 4.2.7
  - 4.2.8
  - 4.2.9
  - '5.0'
  - 5.0.1
  - 5.0.2
  - 5.0.3
  - 5.0.4
  - 5.0.5
  - 5.0.6
  - 5.0.7
  - 5.0.8
  - '5.1'
